wordpress-mobile/release-toolkit

lib/fastlane/plugin/wpmreleasetoolkit/actions/gp_downloadmetadata_action.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/metadata_download_helper.rb

Moves metadata downloader from the app repo to this plugin

Moves metadata downloader to the plugin

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.1.5 into develop

Merge release/0.1.5 into develop

---

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_validate_action.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/configure_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge Release/0.1.5 into Master

Merge Release/0.1.5 into Master

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Bump version to 0.1.7

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Bump version to 0.2.0

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.2.1 into develop

Merge release/0.2.1 into develop

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.2.2 into Master

Merge release/0.2.2 into Master

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.2.2 into Develop

Merge release/0.2.2 into Develop

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release 0.4.0 into develop

Merge release 0.4.0 into develop

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release 0.5.0 into develop

Merge release 0.5.0 into develop

---

.circleci/config.yml
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_betabuild_prechecks.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_bump_version_beta.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_bump_version_hotfix.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_hotifx_prechecks.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_tag_build.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_git_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_version_helper.rb

Merge Feature/android beta hotfix into release/0.6.0

Merge Feature/android beta hotfix into release/0.6.0

---

lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_bump_version_final_release.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_bump_version_hotfix.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_codefreeze_prechecks.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_create_xml_release_notes.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_current_branch_is_hotfix.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_finalize_prechecks.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/close_milestone_action.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/create_new_milestone_action.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/removebranchprotection_action.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_git_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_version_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/ghhelper_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/metadata_download_helper.rb

This PR adds some actions in order to improve the Android release finalization. 
It can be tested in the companion: https://github.com/wordpress-mobile/WordPress-Android/pull/10176

Improve Android finalize release

---

lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_build_prechecks.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_bump_version_hotfix.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_bump_version_release.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_hotifx_prechecks.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge fixes to release/0.2.0 into release/0.6.0

Merge fixes to release/0.2.0 into release/0.6.0

---

lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_bump_version_final_release.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_bump_version_hotfix.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_codefreeze_prechecks.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_create_xml_release_notes.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_current_branch_is_hotfix.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_finalize_prechecks.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/close_milestone_action.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/create_new_milestone_action.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_build_prechecks.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_bump_version_release.rb
lib/fastlane/plugin/wpmreleasetoolkit/actions/removebranchprotection_action.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_git_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_version_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/ghhelper_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/metadata_download_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/promo_screenshots_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge 0.6.0 into develop

---

docs/Release Notes.md

This PR adds some information about the release notes handling.

Add release notes doc

---

lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_git_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb

Related to https://github.com/wordpress-mobile/WordPress-Android/pull/10963

Push current branch only, don't rely on local git config

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.8.2 into develop

Merge release/0.8.2 into develop

---

CONTRIBUTING.md
lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_git_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb
lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge `release/0.8.2` into `master`.

Release 0.8.2

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.9.0 into develop

Merge release/0.9.0 into develop

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.9.1 into develop

Merge release/0.9.1 into develop

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.9.2 back into develop

Merge release/0.9.2 back into develop

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.9.4 back into develop

Merge release/0.9.4 back into develop

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.9.5 into develop

Merge release/0.9.5 into develop

---

lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release 0.9.6 back into develop

Merge release 0.9.6 back into develop

---

Gemfile.lock
lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.9.8 into develop

Merge release/0.9.8 into develop

---

Gemfile.lock
lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.9.9 into develop

Merge release/0.9.9 into develop

---

Gemfile.lock
lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge Release/0.9.11 back into develop

Merge Release/0.9.11 back into develop

---

Gemfile.lock
lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge Release/0.9.12 back into develop

Merge Release/0.9.12 back into develop

---

Gemfile.lock
lib/fastlane/plugin/wpmreleasetoolkit/version.rb

Merge release/0.9.13 back into develop

Merge release/0.9.13 back into develop
