.gitignore, lib/fastlane/plugin/wpmreleasetoolkit.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_add_files_to_copy_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_download_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_setup_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_update_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_validate_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/configure_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/filesystem_helper.rb
Adds a set of fastlane actions to allow dealing with configuration secrets.
**To Test:**
1. Add the Release Toolkit to a project's `Pluginfile`, then update your dependencies.
2. Run `bundle exec fastlane run configure_setup` (works from anywhere in the project that calling `fastlane` works). You'll be prompted to either install the sample data, or install from another git repository you have access to. For testing purposes, it's probably easiest to use the sample data.
3. Next, you'll be prompted to add any files you wish to be copied from the secrets repository to your project. Type `y` for yes, then feel free to just us the examples provided. For the source, you have to enter a valid file path, but for the destination, you can use any path, so enter a path that won't overwrite an …
=> Add Configuration Validation

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_validate_action.rb
The error message if there’s no `.configure` file isn’t very helpful – this adds a check to tell the user to run `configure_setup` rather than “The commit hash doesn’t match”
=> Check that configure file exists before validating

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_validate_action.rb
Better handle local configuration changes
If someone changes the config locally (by modifying an existing file), the error messaging may not be helpful. This changes improves that.
The old test case only handled new files or folders – this now handles both types of change better.
Depends on #7
=> Reorder configuration checks

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_update_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_validate_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/configure_helper.rb
This PR adds support for validating individual files, rather than the whole repo. It's backwards-compatible with older `.configure` files, too – so this shouldn't really break anything.
**How to test:**
On an Android project, update the `.configure` file, setting the `pinned_hash` to a commit hash from the secrets repo – pick one from way back, so that there will have been changes that affect the files in the project. If you run `bundle exec fastlane run configure_validate`, you'll get an error listing which files have changed, and prompting you on how to fix the issue. Following the instructions will resolve the problem for you.
Next, pick a commit hash that isn't the most recent, but that's new enough that there are no new changes to files used by this project. The validation will pass. …
=> Add per-file validation

lib/fastlane/plugin/wpmreleasetoolkit/actions/an_localize_libs_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/android_localize_helper.rb
This PR adds the localize_libs action to merge strings from libraries to the app file in Android. 
The code has been extracted from the localize.rb script in the WooCommerce Android app and added to the plugin in order to reuse it in WPAndroid.
=> Add localize_libs_action 

lib/fastlane/plugin/wpmreleasetoolkit/actions/get_prs_list_action.rb
This PR handles the `404 - Not Found` error in the `get_prs_list_action`.
The error is related to the way the action works: it scans the git log and parses the _merge_ messages in order to create the list of merged PRs, then it queries GitHub for every PR in order to get the data. If a commit message contains the same string used by GitHub for a PR merge, but it references something different, the query fails. 
The specific case we found was a corner one: 
- in a branched repository, a bunch of PRs have been merged into a _master_ branch. GH merge messages have been commited to that branch.
- at the end of the work, a PR has been opened to merge the _master_ branch from the branched repository into the main repository.
This way, all the merge messages related to the branched repository …
=> Fix error 404 not found

Gemfile.lock, fastlane-plugin-wpmreleasetoolkit.gemspec
`octokit` is used in https://github.com/wordpress-mobile/release-toolkit/blob/develop/lib/fastlane/plugin/wpmreleasetoolkit/helper/ghhelper_helper.rb but not declared as a dependency. This adds it to the gemspec.
=> Add missing octokit dependency

Gemfile.lock, fastlane-plugin-wpmreleasetoolkit.gemspec
It turns out the `git` gem was also missing from the Gemspec. Adding it here.
=> Add missing git gem dependency

lib/fastlane/plugin/wpmreleasetoolkit/actions/setbranchprotection_action.rb
I removed `SetbranchprotectionAction` in wordpress-mobile/release-toolkit#24 but @loremattei pointed out that we now can't delete release branches 🤦‍♂️ 
This adds it back in but removes the BuudyBuild required check. Since this is used in more than one repo, a hardcoded check here doesn't make sense.
Reverts wordpress-mobile/release-toolkit#24
=> Re-add SetbranchprotectionAction action and remove BuddyBuild status check

lib/fastlane/plugin/wpmreleasetoolkit.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_betabuild_prechecks.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_build_prechecks.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_build_preflight.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_bump_version_beta.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_bump_version_hotfix.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_bump_version_release.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_clear_intermediate_tags.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_codefreeze_prechecks.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_current_branch_is_hotfix.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_final_tag.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_finalize_prechecks.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_get_app_version.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_hotifx_prechecks.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_localize_project.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_tag_build.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_update_metadata.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_update_release_notes.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_version_helper.rb
This PR adds some actions that help to handle iOS releases. The actions have been extracted from WPiOS and can be tested in this WooCommerce iOS PR: https://github.com/woocommerce/woocommerce-ios/pull/802
=> Add lanes for iOS releases

lib/fastlane/plugin/wpmreleasetoolkit/helper/android_localize_helper.rb
The PR over at https://github.com/wordpress-mobile/WordPress-Android/pull/9368 is failing due to the CircleCI `strings-check`.
**To Test**
1) In `wordpress-android`, run `bundle exec fastlane validate_login_strings pr_url:https://github.com/wordpress-mobile/WordPress-Android/pull/9368`. Note the failing lane.
2) Use this branch in that project, and run the command again. It should succeed this time.
I'm not 100% sure that this fix resolves the root cause, but applying the fix makes the checks pass, which makes me think that it's an appropriate solution. Let me know if not!
=> Fix a bug in `verify_diff` for some diff strings

lib/fastlane/plugin/wpmreleasetoolkit.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_codefreeze.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_current_branch_is_hotfix.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_finalize_prechecks.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_update_metadata.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_git_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_version_helper.rb
This PR adds some actions that help to handle Android releases. The actions have been extracted from WPAndroid and can be tested in this WooCommerce Android PR: https://github.com/woocommerce/woocommerce-android/pull/924.
=> Add actions for Android releases

lib/fastlane/plugin/wpmreleasetoolkit/helper/an_metadata_update_helper.rb
This PR updates `release-toolkit` to fix a bug in `update_appstore_strings` where the new release notes sometimes are not added to the .pot file.
It can be tested in the related client PR here: https://github.com/woocommerce/woocommerce-android/pull/1079
=> Fix regex to remove leading zeros

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_download_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_update_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_validate_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/configure_helper.rb
Currently in the WCAndroid/WPAndroid projects, running the command `bundle exec fastlane install configure_apply` ignores the `pinned_hash` and `branch` in `.configure`.  This has the potential to introduce bugs if the `mobile-secrets` repo is at a different hash.  
We can avoid this by checking to see if the secrets repo is on the correct hash (both branch and commit) and, if not, go ahead and check out `pinned_hash` before copying any files.  If the secrets repo is already on the correct branch and commit, then do nothing and go ahead with the file copy.
**To test:**
* Change Fastlane’s Pluginfile in WCAndroid/WPAndroid to point to this fork and branch, like so:
`gem 'fastlane-plugin-wpmreleasetoolkit', git: 'https://github.com/markpar/release-toolkit', branch: …
=> Ensure secrets repo is on correct hash before copying files

lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_build_prechecks.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_build_preflight.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_bump_version_release.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_get_alpha_version.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_get_release_version.rb
This PR adds some actions required to support the new Android builds. 
It can be tested with the companion PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10143
=> Add actions to support Android builds

fastlane-plugin-wpmreleasetoolkit.gemspec, lib/fastlane/plugin/wpmreleasetoolkit/helper/promo_screenshots_helper.rb
This PR makes RMagick an optional dependency for the release toolkit. 
The reason for this is that the RMagick pod seems to be quite troublesome to install for a lot of people (and on CI) and, since it's required only by Promo Screenshots so far, it makes sense to require it only when that feature is used. 
There's a companion PR in WPiOS to test the changes here: https://github.com/wordpress-mobile/WordPress-iOS/pull/12133
=> Make RMagick optional

.circleci/config.yml, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_betabuild_prechecks.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_bump_version_beta.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_bump_version_hotfix.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_hotifx_prechecks.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_tag_build.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_git_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_version_helper.rb
This PR adds some actions to support beta and hotfix versioning on Android.
The actions can be tested in the companion PR on WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/10156.
=> Add actions for Android beta/hotfix versioning

lib/fastlane/plugin/wpmreleasetoolkit/helper/promo_screenshots_helper.rb
This PR changes the way the load error message for RMagick is shown. Currently, it's shown every time the plugin is loaded. With the changes in this PR, it will be shown only when the PromoScreenshot action is called. 
This can be tested as a part of https://github.com/wordpress-mobile/WordPress-iOS/pull/12133.
=> Fix PromoScreenshots error message

.circleci/config.yml, .gitignore, Gemfile.lock, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_validate_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/configure_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/models/configuration.rb, spec/configuration_spec.rb, spec/ghhelper_action_spec.rb
I'm starting to work on some changes to make the configure tool more powerful. As a first step I have extracted the logic for the configuration into a model of its own with tests. There are no functional changes here.
I have also added config to run the tests on CI.
To Test:
- See that CI passes.
- Point a repo with a `.configure` file to this branch (`gem 'fastlane-plugin-wpmreleasetoolkit', git: 'https://github.com/wordpress-mobile/release-toolkit', branch:'configure-object' 
`).
- Run `bundle install`.
- Run `bundle exec fastlane run configure_apply` and `bundle exec fastlane run configure_validate`. It should work exactly as before.
=> Add model for secrets configuration

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_update_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/models/configuration.rb, spec/configuration_spec.rb
This is a simple change to add a `project_name` entry to `.configure` that defaults to the name of the project directory. It's not used for anything yet but will allow for project-specific config (such as encryption keys) to be stored in the secrets repo (see https://github.com/wordpress-mobile/release-toolkit/pull/69).
It will be added to existing projects the next time `configure_update` is run.
For new projects:
1. Checkout this branch and run `bundle install`.
2. Run `bundle exec fastlane run configure_setup`, choosing not to copy any files and see that `.configure` has a `project_name` entry.
For existing projects
1. Remove the `project_name` path from the `.configure` created above.
2. Run `bundle exec run configure_update` and see that `.configure` now has a `project_name` entry. …
=> Add 'project_name' to .configure

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_add_files_to_copy_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_update_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/configure_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/encryption_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/filesystem_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/models/configuration.rb, lib/fastlane/plugin/wpmreleasetoolkit/models/file_reference.rb, spec/configuration_spec.rb, spec/encryption_helper_spec.rb, spec/file_reference_spec.rb
This is a follow up to https://github.com/wordpress-mobile/release-toolkit/pull/68.
As discussed, we would like a way to access files from the secrets repo on CI without needing access to the repo itself. The solution is to provide a new `"encrypt" : true` option in the `.configure` file. When this is enabled, `configure_update` will save an encrypted version of the file to `.configure-files` in the project and `configure_apply` will decrypt that instead of copying the file from the secrets repo (so access is not needed).
There are no breaking changes and the existing workflow still works exactly as before.
In the next PR I will add the logic needed for generating and storing encryption keys in the secrets repo. At the moment it just uses a `CONFIGURE_ENCRYPTION_KEY` environment variable. …
=> Add support for storing configured files encrypted in project itself

lib/fastlane/plugin/wpmreleasetoolkit.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/an_localize_libs_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/an_update_metadata_source_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/android/an_validate_lib_strings_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/close_milestone_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/create_new_milestone_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/get_prs_list_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/gp_downloadmetadata_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/gp_update_metadata_source.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/promo_screenshots_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/removebranchprotection_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/setbranchprotection_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/setfrozentag_action.rb
This PR moves some actions from the `actions` folder to the proper subfolder in order to give a better organization to the repository. 
1. Update your `Pluginfile` to point to this branch.
2. Run `bundle install`.
3. Run `bundle exec fastlane actions` and verify that the moved actions are still listed. 
4. Try to run some actions and verify that they are executed without errors. For example: `bundle exec fastlane get_pullrequests_list start_tag:13.0`.
=> Refactor actions folder

lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_build_preflight.rb
This PR updates the iOS Build Preflight action to use the `configure_apply` instead of `configure_validate` during the initial check.
This way, the commit referenced in the `.configure` file is checked out in the mobile secrets repository before starting the build.
This PR is related to https://github.com/wordpress-mobile/WordPress-iOS/pull/12207 and can be tested from there.
=> Use configure_apply instead of validate

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_setup_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_update_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/configure_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/encryption_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/filesystem_helper.rb, spec/encryption_helper_spec.rb
This is a follow up to https://github.com/wordpress-mobile/release-toolkit/pull/69.
This makes the previously added encryption functionality useful by adding a way for keys to be generated and stored in the secrets repo. Now, when `configure_setup` or `configure_update` is run, a new key is generated and saved in `~/mobile-secrets/keys.json`, if once odesn;t already exist. That is then used for all subsequent encryption/decryption options. If a `CONFIGURE_ENCRYPTION_KEY` env variable is present, that will be used instead (we will use that on CI).
1. First, switch your mobile secrets branch so that testing doesn't modify master: `cd ~/.mobile-secrets && git checkout -b key-generation && git push -u origin key-generation`.
2. Back in the release toolkit, run `bundle install` and then …
=> Generate and store project keys in keys.json when configure_update or configure_setup is run

Gemfile.lock, fastlane-plugin-wpmreleasetoolkit.gemspec, lib/fastlane/plugin/wpmreleasetoolkit/version.rb
Bumping the version so that the changes for encryption in #68, #69, #70 and #71 can be used in our projects.
=> Bump version to 0.7.0

Gemfile.lock, fastlane-plugin-wpmreleasetoolkit.gemspec
This PR updates Nokogiri to 1.10.4 to fix a security alert.
=> Update Nokogiri to fix a security alert

lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_betabuild_prechecks.rb
This PR fixes a bug in `android_betabuild_prechecks` where the `versionCode` for `alpha` builds was not evaluated correctly. 
The PR can be tested in https://github.com/wordpress-mobile/WordPress-Android/pull/10421
=> Fix alpha version code evaluation

lib/fastlane/plugin/wpmreleasetoolkit/helper/encryption_helper.rb
This is a small enhancement to the encryption/decryption functionality to force it to always use UTF-8 strings.
Without this, everything works fine but the tool sometimes thinks that binary files (such as the keystore in https://github.com/wordpress-mobile/WordPress-Android/pull/10404) have changed, when they haven't.
=> Force encryption/decryption to use UTF8 strings

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb
@malinajirka came across an issue this morning when running `bundle exec fastlane run configure_apply` where the repo wouldn't be checkout correctly and it failed.
It turns out we were using `File.file?` to check if the repo is present, but that only works for files (not directories). This is a small update to use the more correct `File.exists?`.
Additionally, the logic to restore the repo back to its original state wasn't working correctly so I have refactored `prepare_repository` to fix that.
To test:
- Checkout an old secrets repo hash: `cd ~/.mobile-secrets && git reset --hard HEAD~10`.
- Point a project at this branch that has a newer hash in `.configure` that you checked out above and run `bundle exec fastlane run configure_apply`.
- It should work and your `~/.mobile-secrets` …
=> Fix configure_apply repo checkout

lib/fastlane/plugin/wpmreleasetoolkit/helper/android/android_version_helper.rb
With https://github.com/wordpress-mobile/WordPress-Android/pull/10404 we broke the versioning automation for WPAndroid, basically because the script relies on a simple `grep` to extract the version information. 
Since almost every action checks the version of the branch before doing anything, the toolkit is completely unusable on WPAndroid.
This PR is not a good fix, it's just a stop-gap solution to allow us to continue to use the toolkit with WPAndroid.
For a clean solution, the easiest way is probably to create dedicated tasks in gradle that can be triggered by the Fastlane gradle action.
Since we also have to make changes to this code to accommodate the different Simplenote versioning scheme, I think that doing all the changes together would be the most effective flow, though it would …
=> Temp fix for the android version helper

lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb
This PR makes the release-notes handling on iOS consistent with the Android one. 
`release-notes.txt` (the source for the .po file) is not overwritten anymore during the code freeze and it's only updated with the final version of the release notes by the release manager.
=> Don't overwrite release-notes.txt during code freeze

lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_build_preflight.rb
The `gym` command allows customization, so we want to here as well.
This will allow customizing the DerivedData path in our tooling, which makes it possible to run a release lane while keeping Xcode open.
**For Discussion**
Instead of doing this by hand, we could use the `clear_derived_data` [action](https://docs.fastlane.tools/actions/clear_derived_data/) instead – either way, we'd need to pass the path into this action.
=> Allow customizing the DerivedData path

lib/fastlane/plugin/wpmreleasetoolkit/helper/git_helper.rb, spec/git_helper_spec.rb
As discussed [in this thread](https://github.com/woocommerce/woocommerce-ios/pull/1314), this PR adds support for checking the state of a directory for various Git things, including determining:
- Is this directory actually a Git repository?
- Does this Git repository have `git-lfs` enabled?
**To Test**
- Take a look through the code for the test cases. If that looks good, and the tests pass, this should be good to go!
=> Add a Git Helper to determine repo and LFS state

lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb
This PR adds a small change to `git_helper::localize_project` to fix an issue where the action fails if there are no changes in the strings because it tries to run a `git commin` with no staged changes.
=> Prevent localize_project to fail if there are no changes

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb
Since we have started running `configure_apply` more regularly on WordPress-iOS (https://github.com/wordpress-mobile/WordPress-iOS/pull/12609), @frosty pointed out that the output is a little noisy.
Here is the output of `bundle exec fastlane run configure_apply` now:
```
[✔] 🚀
[10:48:42]: -----------------------------
[10:48:42]: --- Step: configure_apply ---
[10:48:42]: -----------------------------
[10:48:42]: Applied configuration
[10:48:42]: Result: true
```
If you wish to test this manually, you can run `bundle exec fastlane run configure_apply` on this branch.
=> configure_apply: Don't print commands and their output

lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/version.rb
This PR adds a check for a repo status before attempting to commit when localizing the project. Since this will fail with a non-zero exit code if there's no new strings
=> Add check for dirty repo when localizing iOS project

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb
Checks to ensure that the decryption key is present before running `configure_apply` – this prevents inscrutable errors from popping up.
=> Add configure_apply preflight

lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_build_prechecks.rb
This PR adds a check to the _android build prechecks_ set that assures that the build is run on a `release` branch. 
This will help avoid that release builds are created out of the `develop` branch by mistake and will be especially useful as we start to autoupload artificats to the Play Store. 
1. Update the `Pluginfile` in your project to make it use this branch. 
2. In your project, checkout the `develop` branch.
3. Run `bundle exec fastlane build_pre_releases` and verify that an error is raised. 
4. In your project, checkout a `relase/xx` branch.
5. Run `bundle exec fastlane build_pre_releases` and verify that the build succeeds.
=> Build Android artifacts only out of release branches

lib/fastlane/plugin/wpmreleasetoolkit/actions/common/create_release_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/ghhelper_helper.rb
This PR adds an action to draft a new release on GitHub and upload release notes and some assets.
It can be tested as a part of https://github.com/wordpress-mobile/WordPress-iOS/pull/13503.
=> Add action to create releases on GitHub

lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_update_metadata_source.rb
This PR imports a lane that is currently hosted in the currently repositories. It has exactly the same code in all the clients (WPiOS, WCiOS and Simplenote iOS), so I'm just moving it here and removing it from the clients. 
Related PRs: [WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/13728), [WCiOS](https://github.com/woocommerce/woocommerce-ios/pull/2039), [Simplenote](https://github.com/Automattic/simplenote-ios/pull/710)
=> Add iOS update metadata source lane

lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_update_action.rb
This PR updates the `configure_update` action to call other actions with the proper syntax, instead of a deprecated one. 
This can be tested in https://github.com/wordpress-mobile/WordPress-Android/pull/11630
=> Fix: move away from deprecated syntax to call other actions

lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_localize_project.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb
This PR fixes two iOS localization issues: 
- it makes sure that the latest version of the pods is installed before localization.
- it makes sure that `localizable.strings` is committed when there are changes. 
This can be tested in https://github.com/woocommerce/woocommerce-ios/pull/2125
=> Fix iOS localization

lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_check_beta_deps.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_completecodefreeze_prechecks.rb
This PR adds two new lanes to iOS that supports the new flow where beta pods are released after the release branch cut. 
This can be tested as a part of:  https://github.com/wordpress-mobile/WordPress-iOS/pull/14107
=> Add ios code freeze split

lib/fastlane/plugin/wpmreleasetoolkit/actions/android/an_update_metadata_source_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/an_metadata_update_helper.rb
This PR adds support for handling a second version of the release notes in the `.po` file. This is meant to be used to upload a shorter version of the release notes as a fallback for the cases where the translation for the original doesn't fit the Play Store limits.
This can be tested as a part of https://github.com/wordpress-mobile/WordPress-Android/pull/12017
=> Short release notes  on Android: upload

lib/fastlane/plugin/wpmreleasetoolkit/actions/android/an_update_metadata_source_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/an_metadata_update_helper.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/metadata_download_helper.rb
This PR is a follow up to https://github.com/wordpress-mobile/release-toolkit/pull/122 and adds the download of the shorter release notes version.
This can be tested as a part of https://github.com/wordpress-mobile/WordPress-Android/pull/12019.
=> Short release notes on Android: Download

lib/fastlane/plugin/wpmreleasetoolkit/actions/common/create_release_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/actions/common/extract_release_notes_for_version_action.rb, lib/fastlane/plugin/wpmreleasetoolkit/helper/ghhelper_helper.rb
On Android we create pre-releases on GitHub with the related .apk file on every beta release. 
This PR tweaks the GitHub release creation in order to add an option to create pre-releases and add a new lane to extract the draft release notes so that they can be attached to the pre-releases.
It can be tested as a part of https://github.com/woocommerce/woocommerce-android/pull/2573.
=> Create GitHub releases on Android

lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_build_prechecks.rb
This PR disables:
- The branch name check on CI. Since the build is started on tags, there's less risk of building something unwanted. Also, due to the way the CI does the checkouts on tags (shallow checkout on the tag itself, not the branch), the branch name is not actually available on CI. We could get it pulling the entire repository and verifying that the tagged commit is on a release branch, but it adds time on CI (pulling the repo can be quite slow) and I don't think it adds a lot of value on CI.
- The git status clean check on CI. We use some temp files on CI to handle the cache, some notification messages, etc. They don't impact the build at all, but due to the way automatic cache works on CircleCI, they have to stay inside the project folder, so the project is technically "dirty" …
=> Fix Android build on CI

lib/fastlane/plugin/wpmreleasetoolkit/helper/an_metadata_update_helper.rb
This PR tweaks the action that updates the PO file for Android metadata strings in order to omit the `release_notes_short` key update if the source file is empty. 
This can be tested as a part of https://github.com/wordpress-mobile/WordPress-Android/pull/12452
=> Don't update Android release_notes_short if the source file is empty

docs/screenshot-compositor.md
Just fixing some typos (and nitpicking spacing inconsistencies while at it) in the `screenshot-compositor.md` documentation
=> Fix: small typos in docs

.circleci/config.yml, Gemfile.lock
This fixes #139 : caching issue with the CircleCI config
The keys used to save and restore the cache on CircleCI were not matching
Use YAML anchors and references to ensure the keys will always match (as we'll reference)
While this PR is in draft state:
* push a dummy change to the Gemfile.lock
* Let the CI run in order to generate a new cache
* push a dummy change on a dummy file other than `Gemfile.lock` or `Brewfile`
* Let the CI run and check that it is re-using the previous cache
* Revert the 2 dummy changes
* Undraft the PR
=> [Internal] Fix: cache issue in CircleCI

lib/fastlane/plugin/wpmreleasetoolkit/actions/common/close_milestone_action.rb
Found some copy/paste in description and a typo in ENV var.
Not sure if you want to actually fix the typo in ENV var because that would break the scripts of anyone depending on that env var though.
=> Fix: typos in fastlane's close_milestone_action description

lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_git_helper.rb, spec/promo_screenshots_helper_spec.rb
As per [this Simplenote macOS PR](https://github.com/Automattic/simplenote-macos/pull/605) we'll need to track `Localizable.strings` + `MainMenu.strings`.
In this PR we're extending the `localize_project` and `update_metadata` script(s), so that multiple `.strings` files can be tracked / pushed.
@loremattei Sir, may I bug you with this one?
/cc @mokagio 
Thanks in advance!!
=> Tracking multiple localizations

fastlane-plugin-wpmreleasetoolkit.gemspec, lib/fastlane/plugin/wpmreleasetoolkit/helper/promo_screenshots_helper.rb
This PRs replaces a deprecated constant of RMagick we use in our `promo_screenshots` action in order to be able to update RMagick to a version compatible with imagemagick 7
Our `promo_screenshots_helper` code – used by the `fastlane create_promo_screenshots` lane in WPAndroid – relies on `RMagick 3.2.x` and currently uses a now-deprecated constant `CopyOpacityCompositeOp`.
The issue is, `RMagick` depends on `imagemagick`, but the latest version of `imagemagick` installed by `brew install` is imagemagick 7, which [the `RMagick` version 3.2.x we're currently using isn't compatible with](https://github.com/rmagick/rmagick/issues/256).
This means I'll need to update `RMagick` to `~> 4.1` for it to be able to work with imagemagick 7 (and with anyone doing a fresh `brew install imagemagic` on a …
=> Replace deprecated constant of RMagick
